development:
  adapter: postgresql
  database: progress_development
  host: localhost

test:
  adapter: postgresql
  database: progress_test
  host: localhost

production:
  adapter: postgresql
  database: progress_production
  host: localhost